server:
  port: 8200
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: financial

  #配置数据源
  datasource:
    url: jdbc:mysql://localhost:3306/project
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
    tomcat:
      min-idle: 10
      max-wait: 50
      max-active: 10000
      max-idle: 100
  #设置thymeleaf的配置
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: LEGACYHTML5
#mybatis的配置
mybatis:
  mapper-locations: mapper/*Mapper.xml
  type-aliases-package: java.util

