server:
  port: 8888
spring:
  redis:
    port: 6379
    host: 192.168.109.128
    jedis:
      pool:
        max-active: 1000
        max-idle: 100
        min-idle: 10
        max-wait: 10000
  application:
    name: zjclient-service
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  datasource:
    username: xzj
    password: 123
    tomcat:
      max-idle: 100
      min-idle: 10
      max-active: 10000
      max-wait: 100
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.52.128.159:3306/logistics   #连接远程网上共享的数据库
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

mybatis:
  mapper-locations: mapper/*Mapper.xml
  type-aliases-package: java.util
  configuration:
    call-setters-on-nulls: true
