server:
  port: 9000
  servlet:
    context-path: /
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: gateway-service
  #配置数据源
  datasource:
    url: jdbc:mysql://47.52.128.159:3306/logistics
    driver-class-name: com.mysql.jdbc.Driver
    username: xzj
    password: 123
    tomcat:
      min-idle: 10
      max-wait: 50
      max-active: 10000
      max-idle: 100
  #设置thymeleaf的配置
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: LEGACYHTML5
#mybatis的配置
mybatis:
  mapper-locations: mapper/*Mapper.xml
  type-aliases-package: java.util
#数据库操作日志
logging:
  level:
    org.java.dao: debug

#自定义路由规则
zuul:
  routes:
    admin-service: /gateway/admin/**
    attendance-service: /gateway/attend/**
  host:
    socket-timeout-millis: 10000
    connect-timeout-millis: 10000
ribbon:
  ReadTimeout: 9000
  ConnectTimeout: 9000
