server:
  port: 8765
  servlet:
    context-path: /
#在eureka服务中心注册客户端
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#指定服务器名称
spring:
  application:
    name: attendance-service
  #配置数据源
  datasource:
    url: jdbc:mysql://47.52.128.159:3306/logistics?useAffectedRows=true
    driver-class-name: com.mysql.jdbc.Driver
    username: xzj
    password: 123
    tomcat:
      min-idle: 10
      max-wait: 50
      max-active: 10000
      max-idle: 100
  #配置工作流
  activiti:
    #自动生成数据库
    database-schema-update: true
    #不要检测当前项目是否包含bpmn文件
    check-process-definitions: false
  #设置thymeleaf的配置
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: LEGACYHTML5
    #redis的配置
  redis:
    host: 192.168.136.128
    port: 6379
    jedis:
      pool:
        min-idle: 10
        max-idle: 50
        max-wait: 10000
        max-active: 1000
#mybatis的配置
mybatis:
  mapper-locations: mapper/*Mapper.xml
  type-aliases-package: java.util

logging:
  level:
    org.java.dao: debug