server:
  port: 8100
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: communication-service
  thymeleaf:
    encoding: UTF-8
    cache: false
    mode: LEGACYHTML5
  datasource:
    url: jdbc:mysql:///y2item
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
  hystrix:
    enabled: true
mybatis:
  type-aliases-package: java.util
  mapper-locations: mapper/*Mapper.xml
